### ISSUE TITLE
Build error on Ruby 2.3.0-preview2 / OS X 10.11.2

### ISSUE THREAD

**Issue by fukayatsu** [eagletmt/faml#47]
```
$ ruby -v
ruby 2.3.0preview2 (2015-12-11 trunk 53028) [x86_64-darwin15]

$ gem install faml -v '0.7.1'
Building native extensions.  This could take a while...
ERROR:  Error installing faml:
	ERROR: Failed to build gem native extension.

    current directory: /Users/fukayatsu/.rbenv/versions/2.3.0-preview2/lib/ruby/gems/2.3.0/gems/faml-0.7.1/ext/attribute_builder
/Users/fukayatsu/.rbenv/versions/2.3.0-preview2/bin/ruby -r ./siteconf20151212-60674-vnsm4v.rb extconf.rb
creating Makefile

current directory: /Users/fukayatsu/.rbenv/versions/2.3.0-preview2/lib/ruby/gems/2.3.0/gems/faml-0.7.1/ext/attribute_builder
make "DESTDIR=" clean

current directory: /Users/fukayatsu/.rbenv/versions/2.3.0-preview2/lib/ruby/gems/2.3.0/gems/faml-0.7.1/ext/attribute_builder
make "DESTDIR="
compiling attribute_builder.cc
In file included from attribute_builder.cc:1:
In file included from /Users/fukayatsu/.rbenv/versions/2.3.0-preview2/include/ruby-2.3.0/ruby.h:33:
In file included from /Users/fukayatsu/.rbenv/versions/2.3.0-preview2/include/ruby-2.3.0/ruby/ruby.h:29:
In file included from /Users/fukayatsu/.rbenv/versions/2.3.0-preview2/include/ruby-2.3.0/ruby/defines.h:68:
/Users/fukayatsu/.rbenv/versions/2.3.0-preview2/include/ruby-2.3.0/ruby/missing.h:256:5: error: use of undeclared identifier 'memset_s'
    memset_s(b, len, 0, len);
    ^
1 error generated.
make: *** [attribute_builder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/fukayatsu/.rbenv/versions/2.3.0-preview2/lib/ruby/gems/2.3.0/gems/faml-0.7.1 for inspection.
Results logged to /Users/fukayatsu/.rbenv/versions/2.3.0-preview2/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/faml-0.7.1/gem_make.out
```

How can I help you? :)

**Comment by fukayatsu** [comment]
It works on Ruby 2.3.0-preview1(or Ruby 2.2.3)

```
$ ruby -v
ruby 2.3.0preview1 (2015-11-11 trunk 52539) [x86_64-darwin15]

$ gem install faml -v '0.7.1'
Fetching: faml-0.7.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed faml-0.7.1
```

**Comment by fukayatsu** [comment]
:eyes: https://github.com/ruby/ruby/blob/v2_3_0_preview2/include/ruby/missing.h#L256

**Comment by eagletmt** [comment]
OS X should have memset_s.
Maybe `#include <string.h>` is missing somewhere... I'm not sure it's faml's issue or Ruby's issue.

**Comment by eagletmt** [comment]
Ah, `# include <string.h>` exists right above the `explicit_bzero_by_memset_s` definition :confused:

**Comment by eagletmt** [comment]
I could reproduce it in my Mac OS X 10.11.
When `-std=c++98` is given, string.h doesn't provide `memset_s` .
I'll remove `-std=c++98`.

**Comment by fukayatsu** [comment]
![寿司ゆき:thanks](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/04.png)
